### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by giangndm** [8xFF/atm0s-media-server#69]
Here is list of first version roadmap, we have goal to release with all bellow features

## SDK
- [x] [JS SDK](https://github.com/8xFF/atm0s-media-sdk-js)
- [x] [React/JS SDK Docs](https://8xff.github.io/media-docs/)
- [x] [React SDK](https://github.com/8xFF/atm0s-media-sdk-react)
- [ ] React Native SDK
- [ ] Rust SDK + Docs
- [ ] Meet sample
- [ ] Gather.town clone sample
- [ ] Online SDK demos

## Features

- [x] Room token, peer token https://github.com/8xFF/atm0s-media-server/pull/129
- [x] Auto or Manual Room (for huge room like Gather.town) https://github.com/8xFF/atm0s-media-server/pull/135
- [x] Stream Pub/Sub
- [ ] In room chat
- [x] Metrics https://github.com/8xFF/atm0s-media-server/issues/66
- [ ] Record / Replay / Compose
- [x] Audio Mix-Minus https://github.com/8xFF/atm0s-media-server/pull/126

## Protocols

- [x] WebRTC
- [x] Whip https://github.com/8xFF/atm0s-media-server/pull/76
- [x] Whep https://github.com/8xFF/atm0s-media-server/pull/76
- [ ] Webrtc Stun
- [ ] Webrtc Turn
- [x] SIP UDP
- [x] RTMP

## Cluster

- [ ] Benchmark
- [x] Global scale with Overlay network
- [x] Inner cluster gateway https://github.com/8xFF/atm0s-media-server/pull/106
- [ ] Global gateway
- [x] Embed monitor dashboard https://github.com/8xFF/atm0s-media-server/pull/106
- [x] Prometheus exporter endpoint https://github.com/8xFF/atm0s-media-server/pull/106
- [ ] Kubernetes deploy

## Integration

- [x] Static authentication
- [ ] Dynamics authentication with remote config
- [x] External log integration #132 
- [ ] SIP hooks

**Comment by giangndm** [comment]
Whip/Whep implement https://github.com/8xFF/atm0s-media-server/pull/76

**Comment by giangndm** [comment]
@luongngocminh how about sdk? If have any update please update here

**Comment by IgorAfanasiev** [comment]
Do you have any plans to support flexfec for video?

**Comment by giangndm** [comment]
@IgorAfanasiev We use str0m library for handling WebRTC protocol, then it depends on str0m. But I also have plan to try to implement flexfec in str0m but it not done yet. Are you have any experience with it?

**Comment by giangndm** [comment]
cleanup for new version
